# Generated by Django 5.2.3 on 2025-06-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedAccessToken',
        ),
    ]
