# Generated by Django 5.2.3 on 2025-06-19 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('income_range', models.CharField(blank=True, max_length=50)),
                ('conditions', models.JSONField(default=list)),
                ('medications', models.JSONField(default=list)),
                ('allergies', models.JSONField(default=list)),
                ('surgeries', models.JSONField(default=list)),
                ('family_history', models.JSONField(default=list)),
                ('is_smoker', models.BooleanField(default=False)),
                ('alcohol_use', models.BooleanField(default=False)),
                ('exercise_frequency', models.CharField(blank=True, max_length=20)),
                ('diet_type', models.CharField(blank=True, max_length=20)),
                ('sleep_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('nearest_facility', models.CharField(blank=True, max_length=100)),
                ('facility_distance', models.CharField(blank=True, max_length=50)),
                ('has_insurance', models.BooleanField(default=False)),
                ('insurance_details', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
