# Generated by Django 5.2.3 on 2025-06-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthSubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthprofile',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Health Profile', 'verbose_name_plural': 'Health Profiles'},
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='bp_checked_recently',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='knows_blood_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='weight_category',
            field=models.CharField(blank=True, choices=[('underweight', 'Underweight'), ('healthy', 'Healthy Weight'), ('overweight', 'Overweight'), ('obese', 'Obese')], max_length=12),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='exercise_frequency',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('1-2', '1-2 times/week'), ('3-5', '3-5 times/week'), ('daily', 'Daily')], max_length=20),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
    ]
