# Generated by Django 5.2.3 on 2025-06-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthSubs', '0002_alter_healthprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True),
        ),
    ]
